### ISSUE TITLE
Running crystal deps after modifying shards.yml does not update the installed version

### ISSUE THREAD

**Issue by spalladino** [crystal-lang/shards#107]
On a fresh project, I create a `shard.yml` with the following dependencies:

``` yml
dependencies:
  pg:
    github: will/crystal-pg
    commit: cafe4748b64a9c95ab93b4c19315780e8e254291
```

Running `crystal deps` installs the correct version, and creates a `shard.lock` with the expected contents:

``` bash
$ crystal deps
Updating https://github.com/will/crystal-pg.git
Installing pg (cafe4748b64a9c95ab93b4c19315780e8e254291)
```

``` yml
shards:
  pg:
    github: will/crystal-pg
    commit: cafe4748b64a9c95ab93b4c19315780e8e254291
```

Now, if I want to update to a specific version, let's say `version: 0.7.1`, and I modify both the `shard.yml` and the `shard.lock` accordignly, when I run `crystal deps again` I get a message stating that I'm using version 0.7.1, but the actual contents in the `libs` folder is still behind in commit `cafe474`.

``` bash
$ crystal deps
Updating https://github.com/will/crystal-pg.git
Using pg (0.7.1)
```

I'm not sure if this is the expected way of updating dependencies. However, the output message is definitely quite confusing, as it led me to think that I was actually using version 0.7.1, which did not get installed until I deleted the dependencies folders and installed them again.
