### ISSUE TITLE
git command failed: git ls-tree

### ISSUE THREAD

**Issue by kostya** [crystal-lang/shards#108]
``` yaml
name: bla
version: 0.1.0

dependencies:
  http_parser:
    github: kostya/http_parser.cr

license: MIT
```

```
crystal deps
git command failed: git ls-tree -r --full-tree --name-only v0.8 -- shard.yml (). Maybe you didn't install git?
```

```
git --version
git version 2.8.3
```

if i add line `branch: master` it works.
