### ISSUE TITLE
Informational library dependencies field

### ISSUE THREAD

**Issue by jhass** [crystal-lang/shards#113]
I propose to add a, for now purely informational, field that lists the shared libraries/sonames a shard wishes to link to, in other words a canonical and standard way to list non-Crystal dependencies.

Each entry provides a set of alternatives. For easy entry each entry is a comma separated list opposed to a nested YAML array, whitespace is ignored.

```yml
name: xml_for_sqlite3
shared_libraries:
  - libsqlite3.so.3.8, libsqlite3.dylib.3.8, libsqlite3.so, libsqlite3.dylib
  - libxml2.so, libxml2.dylib
```

If we can establish this as a community standard, then we have a canonical way of looking up a shards dependencies we need to install. Later tools could be built upon it, such as displaying them on a website, checking whether a system has all available upfront or even tools that look up which packages provide them and install those packages.

**Comment by ysbaddaden** [comment]
The base idea is good, but I'm not sure about the proposal.

For example libraries may be static or shared, but `shared_libraries` looks like we can't use `libyaml.a`.

Extensions are dependent to the OS, so we'd have to list `.dll`, `.so` and `.dylib` at least, multiplied by how many versions we want to declare. Maybe there could be a simpler way? Like:

```yml
libraries:
  libsqlite3: 3.8
  libxml2: *
```
