### ISSUE TITLE
postinstall not running after install or update

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/shards#114]
I have a simple `shard.yml` file with a postinstall script, but any time I run `shards install` or `shards update` it never runs the postinstall. I also tried just doing `postinstall: echo "TEST"`

```yaml
name: blog
version: 0.1.0
authors:
  - Me
license: MIT
dependencies:
  guardian:
    github: f/guardian
    branch: master
scripts:
  postinstall: crystal build --release -o ./guardian libs/guardian/guardian.cr
```

I'm running `Crystal 0.18.7 (2016-07-27)` `Shards 0.6.3 (2016-07-27)` on OSX 10.11.6
