### ISSUE TITLE
strange error when branch not found

### ISSUE THREAD

**Issue by kostya** [crystal-lang/shards#128]
```
dependencies:
  myhtml:
    github: kostya/myhtml
    branch: data
```

crystal deps

```
Updating https://github.com/kostya/myhtml.git
git command failed: git tag --list --contains data --column=never (malformed object name data). Maybe you didn't install git?
```

i think it should be more human
