### ISSUE TITLE
Compound version requirement

### ISSUE THREAD

**Issue by mosop** [crystal-lang/shards#135]
Hi. Is there a way to specify a compound version requirement for a dependency?

For example, "newer backwards-compatible versions but need a specific bug fix":

```yaml
dependencies:
  foolib:
    github: someone/foolib
    version: ~> 1.0, >= 1.0.1
```
