### ISSUE TITLE
shards with extensions now not compiled

### ISSUE THREAD

**Issue by kostya** [crystal-lang/shards#139]
```
dependencies:
  myhtml:
    github: kostya/myhtml
    branch: master
```

```
crystal deps
Updating https://github.com/kostya/myhtml.git
Installing myhtml (master)
Postinstall cd ext && make package
Failed cd ext && make package:
/bin/sh: line 1: cd: ext: No such file or directory
```
