### ISSUE TITLE
Issue with postinstall when requiring a branch

### ISSUE THREAD

**Issue by azah** [crystal-lang/shards#143]
my project's yaml:
```yaml
dependencies:
  kemalyst:
    github: azah/kemalyst
    branch: fix_postinstall
```

[That branch has a different shard.yml](https://github.com/azah/kemalyst/blob/fix_postinstall/shard.yml):

```yaml
# old
scripts:
  postinstall: crystal templates/install.cr
# new
scripts:
  postinstall: crystal src/templates/install.cr
```

The postinstall on the new branch fails like on the master branch.

```
Postinstall crystal templates/install.cr
Failed crystal templates/install.cr:
Error: unknown command: templates/install.cr
```

with -v:
```
Installing kemalyst (fix_postinstall)
git ls-tree -r --full-tree --name-only fix_postinstall -- shard.yml
git archive --format=tar --prefix= fix_postinstall | tar -x -f - -C '/Users/andrew/Desktop/Sync/_programming/Crystal/main_site/lib/kemalyst'
git log -n 1 --pretty=%H fix_postinstall
git ls-tree -r --full-tree --name-only HEAD -- shard.yml
git show HEAD:shard.yml
Postinstall crystal templates/install.cr
rm -rf '/Users/andrew/Desktop/Sync/_programming/Crystal/main_site/lib/kemalyst'
Failed crystal templates/install.cr:
Error: unknown command: templates/install.cr
```
