### ISSUE TITLE
Local overrides (was: Shards Link)

### ISSUE THREAD

**Issue by crisward** [crystal-lang/shards#152]
Npm, bower and other package manages have the concept of linking dependencies. This is useful when developing app dependencies. Allowing you to have two projects in different folders, then one is sym-linked into the libs folder of the other.

I think it'd be useful to have this in shards. What do you think?

**Comment by ysbaddaden** [comment]
Maybe use the `path` resolver?

**Comment by RX14** [comment]
The problem with the path resolver is that you need to run `shards update` to copy the new source code every time you make a change. It also required you to modify the shard.yml every time you want to bugfix in a dependency.

**Comment by ysbaddaden** [comment]
Huh? AFAIK `path` creates a symlink...

**Comment by RX14** [comment]
@ysbaddaden Oh, I thought it didn't. I should have checked, sorry.

**Comment by crisward** [comment]
What is the path resolver?

**Comment by ysbaddaden** [comment]
Instead of using a `git` ot `github`, you may:

```yaml
dependencies:
  my_shard_name:
    path: /absolute/path/to/dependency
```

**Comment by crisward** [comment]
got it. Thanks.

**Comment by crisward** [comment]
Still not quite as nice as the link option, with link I don't have to remember to change by path before pushing live... Maybe I could add that to a deploy script..

**Comment by RX14** [comment]
Just tried using `path` on a transitive dependency, it didn't work:
```yml
dependencies:
  db:
    github: crystal-lang/crystal-db
    path: /data/programming/crystal-db/
  pg:
    github: will/crystal-pg
    version: ~> 0.13.1
```

This links crystal-db from github like usual, whichever way I order the listings.
