### ISSUE TITLE
Expected SCALAR but was SEQUENCE_START

### ISSUE THREAD

**Issue by watzon** [crystal-lang/shards#163]
I'm attempting to use the shards build system and I'm getting the error: 

```
in /home/.../librazer/shard.yml:14: Shards::ParseError: Expected SCALAR but was SEQUENCE_START

  1.     options:
  2.       - "-o bin/librazer-dev"
  3. 
           ^
```

Here is my `shard.yml`:

```yaml
name: librazer
version: 0.1.0

authors:
  - Chris Watson <chris@marginzero.co>

crystal: 0.23.0

targets:
  default:
    main: src/librazer.cr
    options:
      - -o bin/librazer
      - --release
  devel:
    main: src/librazer.cr
    options:
      - -o bin/librazer-dev

dependencies:
  dbus:
    github: oprypin/crystal-dbus
    branch: master

license: MIT
```
**System:**
Shards 0.7.1 (2017-06-10)
Crystal 0.23.0 (2017-07-05) LLVM 4.0.1
Manjaro Linux

**Comment by RX14** [comment]
I'm pretty sure the `options` key for a target doesn't exist. `SPEC.md` doesn't specify it and I can't see it in the code.

**Comment by RX14** [comment]
Targets only specify the source file to compile and the name of the executable (only the name, not the path). Extra options such as `--release` would be passed as options to `shards build`.

In your case the correct usage would be this:
```yaml
targets:
  librazer:
    main: src/librazer.cr
```

You'd then use `shards build --release` to compile `bin/librazer` as a release build and leave off `--release` to create a debug build. If you want both at the same time, shards doesn't seem to cater to that currently, or provide any way of providing compiler options.
