### ISSUE TITLE
Non-opensource shards

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/shards#174]
It's not clear how to use install private dependencies for an app. A dependency may be a private git repository, for example.

**Comment by ysbaddaden** [comment]
Duplicate of #79.

Public or private makes no difference: Shards will use whatever Git URL you provide it, so jut use the URL you'd use to clone the repository (e.g. SSH), making sure you have access to the private repository, which is out of Shards' scope. For example:

```yaml
dependencies:
  foo:
    git: git@github.com:user/foo.git
```
