### ISSUE TITLE
Error resolving pre-release version

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/shards#184]
I'm trying to use meta versions as described in SemVer. My lib has `v0.2.0-pre1` tag.

My app's shard looks like this:

```yaml
mylib:
  github: username/mylib
  version: 0.2.0-pre1
```

Getting `Error resolving mylib (0.2.0-pre1)`. What's wrong?
