### ISSUE TITLE
Add option to specify destination directory

### ISSUE THREAD

**Issue by obskyr** [crystal-lang/shards#198]
I recently found myself wanting to use Shards to manage some external tools (as opposed to libraries) in a separate project. There is one problem with that, however: `shards install` is hard-coded to install to `./lib`.

It would be nice to have an option to specify the directory for the actual shards. Let's call the option `-d` (`--directory`), for example - with it, you can run commands like `shards -d external install`, `shards -d tools check`, or `shards -d . update` to have the commands act on your specified directory instead of `lib`.

**Comment by RX14** [comment]
I actually find it quite nice that shatds's design is generic enough to be able to manage things which aren't crystal libraries at all...

**Comment by obskyr** [comment]
I agree! A directory option would make Shards even more useful in that regard.

**Comment by ysbaddaden** [comment]
Trivia: Shards was initially hacked has a replacement for Bower (named Harbour) —I wanted reproducible installs & I was bored to install node + npm to install bower to eventually install browser dependencies on servers. Hence it's no wonder that it's kinda generic :grin: 

That being said, Shards is currently meant to handle Crystal dependencies, and Crystal has a strong opinion on where source code is expected to live. I don't think we'll change that for the time being, unless there is a strong push for keeping/making shards a somewhat generic package manager.

That being said, you can set environment variables to tweak Shards' behavior (see `src/config.cr`). That should be considered private internal detail, and it may break someday, but I rely on these environment variables for running integration tests and that won't change any time soon.

**Comment by obskyr** [comment]
It wouldn't be useful for libraries - since `require` looks in `lib` specifically, a hypothetical `-d` option wouldn't be very helpful for that. However, for tools it's indispensable - and it'd be simple to implement, too (just expose `Shards.install_path=` to a command line option).

I don't think a "strong push" to make Shards more generic is required: you yourself have already submitted a pull request (#126) to allow installing executables (#95). Since that's meant to make Shards more friendly toward installing tools, a feature like this would fit well in with that.

**Comment by obskyr** [comment]
I've realized there's another consideration: when you install a tool, you don't want that tool's dependencies to go into the same directory - you want them to go into the tool's `lib` directory. For example, if you have a tool called `toolie` that depends on a library called `libby`, you want this (`Makefile`s to illustrate a possible way to build the tools afterward):

```
tools/
    external/
        tooly/
            lib/
                libby/
            Makefile
            ...
    Makefile
    shards.lock
    shards.yml
```

But instead, Shards does this:

```
tools/
    external/
        tooly/
            lib/
            Makefile
            ...
        libby/
    shards.lock
    shards.yml
```

This isn't impossible to work with, as in this case `tools/external/tooly/Makefile` will most likely install another copy of `libby` into the tool's `lib` directory, but it *is* redundant.

Getting Shards to play nice with tools may thus be a bit more involved than a simple install directory option (although that's part of it). A worthwhile pursuit, though, as evidenced by the work you've already done on the matter!

**Comment by ysbaddaden** [comment]
I'm sorry but I don't understand where you're going to. That sounds awfully complex. Dependencies are installed under `lib/foo` and its executables, if any, are linked under `bin` for simpler access. Thought this is debatable, and should only be for regularly, manually called tools or executables to distribute along with the application. Tools that are meant to be called during a build chain (e.g. from a Makefile) should be left under `lib/foo/bin` IMHO.

**Comment by obskyr** [comment]
> Tools that are meant to be called during a build chain (e.g. from a Makefile) should be left under lib/foo/bin IMHO.

That isn't really viable as it stands, though, since any dependencies the tool has will be installed to `lib/` instead of `lib/foo/lib`.

A separate `apps` (or `tools` or `programs` or what have you) section in `shards.yml` could solve this:

```yaml
name: projecto
version: 1.5.7

authors:
  - Crystal McCrystalson <sparkly@rocks.wow>

# These have their dependencies installed flatly to lib/
dependencies:
  librario:
    github: dude/librario
    version: ~> 4.3

# These have their dependencies installed independently to lib/<name>/lib/
apps:
  tooly:
    github: bro/tooly
    version: ~> 1.1
```

Or as a property on dependencies:

```yaml
name: projecto
version: 1.5.7

authors:
  - Crystal McCrystalson <sparkly@rocks.wow>

dependencies:
  # librario's dependencies get installed to lib/
  librario:
    github: dude/librario
    version: ~> 4.3
  # tooly's dependencies get installed to lib/tooly/lib/
  tooly:
    app: yes
    github: bro/tooly
    version: ~> 1.1
```

You're right, though, that properly supporting non-binary tool installs is a bit more complicated than it may have seemed at first. There are a couple more considerations, like "should non-library dependencies be installed to `lib/` at all?", for example.
