### ISSUE TITLE
shard.lock file adds new dependency from shards install

### ISSUE THREAD

**Issue by rdp** [crystal-lang/shards#219]
Hello.
I noticed if `shard.yml` has

```yaml
dependencies:
  kemal:
    github: sdogruyol/kemal
    branch: master
```
and `shard.lock` says
```yaml
  kemal:
    github: sdogruyol/kemal
    commit: f916bad09568582a74730a38b40bdeceaab46a10
```

if I do a
```console
$ shards install
```
it adds a *new dependency* into `shard.lock` that is in `kemal/master`, but isn't in the commit I am currently using....

In this case it added 
```diff
+  exception_page:
+    github: crystal-loot/exception_page
```
