### ISSUE TITLE
Shards from gists

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/shards#222]
It may be a good idea to add ability to require small pieces of code without need to maintain a separate repository for it. E.g. I'm using this log formatter in my projects:

https://gist.github.com/vladfaust/0689b06a615834fb0ead01c7a14c029b

And it may be an overhead to copy-paste this code into each project, however the code piece is too small to create a separate shard with issues, builds, README etc.

What if a developer could specify github gist as a dependency?

```yaml
dependencies:
  custom_log_formatter:
    gist: vladfaust/0689b06a615834fb0ead01c7a14c029b
    revision: df1824db3d620139a02187de1c017e4525a37669
```

```crystal
require "custom_log_formatter"

logger = Logger.new(STDOUT, Logger::DEBUG, custom_log_formatter)
```
