### ISSUE TITLE
shards install reports wrong version

### ISSUE THREAD

**Issue by rdp** [crystal-lang/shards#236]
Current output of "shards install" seems a bit confusing.  It says "using version 0.24.0" when it isn't:

$ cat shard.yml 
```
name: kemal_server
version: 0.1.0

authors:
  - rogerdpack <rogerpack2005@gmail.com>

license: MIT

dependencies:
  kemal:
    github: sdogruyol/kemal
    branch: master
```

$ cat shard.lock
```

version: 1.0
shards:

  kemal:
    github: sdogruyol/kemal
    commit: a5870e7d24e5ec75c956bcf3e4423f55a2c4ff78
```

This commit doesn't exactly line up with any tag, though it is "after" tag v0.22.0.
With a `shards install` it installs the right version, a5870e7d24e5.
What I'd expect the output of "shards install" to say:

`Using kemal (a5870e7d2, 7 commits after 0.22.0)`

or even better

`Using kemal (a5870e7d2, 7 commits after 0.22.0, available: 5 commits after 0.24.0)`

What it currently says:

`Using kemal (0.24.0 at master)`

Which is wrong, it's actually using a commit post 0..22.0.

Cheers.
