### ISSUE TITLE
Force dependency version

### ISSUE THREAD

**Issue by duraki** [crystal-lang/shards#240]
Today while upgrading my codebase to 0.27.0; I've stumble upon dependency issue; I couldn't lock a library to specific version. The only similar issue is at #12. Related to [kemalcr/kemal-session#70](https://github.com/kemalcr/kemal-session/issues/70#issuecomment-437711805).

Example of [kemalcr/kemal-csrf](https://github.com/kemalcr/kemal-csrf/blob/master/shard.yml):

```yaml
...
dependencies:
  kemal-session:
    github: kemalcr/kemal-session
    version: 0.10.0 # => locks kemal-session to 0.10.0
```
Example of [crecto/crecto-admin#shard.yml](https://github.com/Crecto/crecto-admin/blob/master/shard.yml#22):

```yaml 
...
  kemal-csrf:
    github: kemalcr/kemal-csrf

  kemal-session:
    github: kemalcr/kemal-session
    
    # => should lock kemal-session to master (0.11.0), but can't since kemalcr/kemal-csrf
    version: 0.11.0
    branch: master 
...
```

As seen above, the first snippet is dependency of the library, in this case `kemal-session`. The second snippet is from "any" project and `shard.yml` listed. 
  
If for some reason we wanted to use latest version of `kemal-session`, we wouldn't be able:

```sh
$ shards update
Fetching https://github.com/schovi/baked_file_system.git
Fetching https://github.com/crecto/crecto.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Fetching https://github.com/kemalcr/kemal-csrf.git
Fetching https://github.com/kemalcr/kemal-session.git
Error resolving kemal-session (0.10.0, 0.11.0) // ERROR
```

Allow developer to run, or force shard lock on base project, rather than parent lib/dep.
