### ISSUE TITLE
Check for dependencies before build

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/shards#266]
I have tried to build multiple projects that can be frustrating because of system dependencies.

example:
the project depends on `libsass`
```yaml
targets:
  test_project:
    main: src/test_project.cr
```

When building targets there are some system dependencies that might be needed.  Is there a way to include a check or something before running the build?

```yaml
targets:
  test_project:
    main: src/test_project.cr
    depends:
      - libsass
```

There might have to be some flags or something for operating systems
