### ISSUE TITLE
Source of shard in shard.lock

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/shards#268]
I have a lot of shards in my yml file, but when I boot my app, it fails on a shard that I never included. When I look in the shard.lock file, I see the shard that fails, but I don't know where it came from. It's obviously included as a dependency of a shard that I did include, but having that information available would be super helpful. Ruby gems does this with the Gemfile.lock 

The activejob gem requires the activesupport and globalid gems as dependencies. 
```
activejob (5.1.4)
    activesupport (= 5.1.4)
    globalid (>= 0.3.6)
```

Showing all the children gets a bit cumbersome in large projects, so maybe we could do something like this where we just show the parent:

```
avram:
  github: luckyframework/avram
  version: 0.9.4
  from: lucky

lucky:
  github: luckyframework/lucky
  version: 0.14.0
```

This would denote that I didn't actually include avram in my shard.yml file, but it was included from lucky which I did include in mine.
