### ISSUE TITLE
Shard install fails with file doesn't exist

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/shards#269]
Using shards version `Shards 0.9.0.rc1 [2781566] (2019-04-25)` when installing [this shard](https://github.com/veelenga/lua.cr)

```yml
name: testing
version: 0.0.1
dependencies:
  lua:
    github: veelenga/lua.cr
    branch: master
```

```
[19:55PM] experiments$ shards install
Resolving dependencies
Fetching https://github.com/veelenga/lua.cr.git
Using lua (0.1.1 at 0f493dbbc7e70c47bc14f6c887df95b9e86a959a)
Failed git ls-tree -r --full-tree --name-only v0.1.1 -- shard.yml (). Maybe a commit, branch or file doesn't exist?
```

I noticed that repo doesn't have any tags or releases. I [forked the repo](https://github.com/jwoertink/lua.cr/) and did a release, and I'm able to install from my fork with no other changes. 

```
[19:59PM] experiments$ shards install
Resolving dependencies
Fetching https://github.com/jwoertink/lua.cr.git
Using lua (0.1.1 at 0f493dbbc7e70c47bc14f6c887df95b9e86a959a)
Writing shard.lock
```

I didn't check if shards 0.8.0 works or not, but since this is the next version, I would think this should work or at least give a better error as to why it doesn't.

**Comment by ysbaddaden** [comment]
There are some issues when the repository doesn't have any tag. The following will fail to find the dependency:

```yaml
dependencies:
  lua:
    github: veelenga/lua.cr
```

An the following will install it but fails afterwards, and doesn't generate a `shard.lock`:
```yaml
dependencies:
  lua:
    github: veelenga/lua.cr
    branch: master
```

Thanks fr reporting!
