### ISSUE TITLE
Renaming a shard leads to failure

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/shards#272]
I have an [a shard](https://github.com/onyxframework/sql) depending on `time_format.cr`:

```yaml
dependencies:
  time_format:
    github: vladfaust/time_format.cr
    version: ~> 0.1.0
```

I've recently renamed the dependency name from `time_format.cr` to [`time-span-humanize`](https://github.com/vladfaust/time-span-humanize), bumping the version and tag from `0.1.1` to `0.2.0`. Unexpectedly, it led to [build failure on CI](https://travis-ci.org/onyxframework/sql/jobs/529776266) with the following message:

```
Fetching https://github.com/vladfaust/time_format.cr.git
Error shard name (time-span-humanize) doesn't match dependency name (time_format)
```

I think it should work, because the `shard.yml` file at `0.1.1` version has proper shard name. IIRC if specifying certain commit or tag instead of version, it would install without any problems.
