### ISSUE TITLE
shards build installs dev dependencies

### ISSUE THREAD

**Issue by KCErb** [crystal-lang/shards#280]
Given a repo `test3` which contains only this `shard.yml`:

```yaml
name: test3
version: 0.0.0
dependencies:
  test2:
    gitlab: crystal-shards-tests/test2
```

and a repo `test2` with only these two files:

```
# shard.yml
name: test2
version: 0.0.0
targets:
  foo:
    main: test.cr
development_dependencies:
  test1:
    gitlab: crystal-shards-tests/test1
scripts:
  postinstall: shards build

# test.cr
puts "Hello World!"
```

and a repo `test1` with these two files:

```
# shard.yml
name: test1
version: 0.0.0
targets:
  boom:
    main: boom.cr
scripts:
  postinstall: shards build

# boom.cr
boom!
```

What would you expect to happen when you run `shards install` in `test3`? You can see for yourself by cloning `test3`: https://gitlab.com/crystal-shards-tests/test3.

I expected that test2 would build its little `foo` executable (that prints hello world) and be done with it. Never touching `test1`'s `shard.yml`. Instead:

```
$ shards install
Fetching https://gitlab.com/crystal-shards-tests/test2.git
Installing test2 (0.0.0 at HEAD)
Postinstall shards build
Failed shards build:
Fetching https://gitlab.com/crystal-shards-tests/test1.git
Installing test1 (0.0.0 at HEAD)
Postinstall shards build
Failed shards build:
Dependencies are satisfied
Building: boom
Error target boom failed to compile:
Error in boom.cr:1: undefined local variable or method 'boom!' for top-level

boom!
^~~~~
```

Is this expected behavior or a bug?

Note that the postinstall / boom stuff in test1 isn't necessary to demonstrate the bug. The point is that test1 is bleeding into test3 even though test2 has only a dev dependency on it. To see the context where this actually hurts a real app see the conversation starting here: https://gitter.im/luckyframework/Lobby?at=5cfa8a2cff3f016baabf4b40.
