### ISSUE TITLE
Will shards.lock be respected in a dependency

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/shards#281]
If I have a dependency eg.
```yaml
shards:
  yolo:
    github: wontruefree/yolo.cr
```

and that dependency has a `shards.lock` file.  Will shards used that lock file when resolving dependencies?
