### ISSUE TITLE
Error with shards update

### ISSUE THREAD

**Issue by remydev** [crystal-lang/shards#289]
Hello,
I have a curious error with the following file 

`shards update` does not stop and returns an error

```
#shard.yml
  name: test
  version: 0.1.0
 
  dependencies:
    pubsubd:
      git: https://git.karchnu.fr/JunkOS/pubsub
    frontd:
      github: Lukc/frontd
    clear:
      github: anykeyh/clear

  targets:
    test:
      main: src/main.cr

```
```
test2 > shards build
Resolving dependencies
Fetching https://git.karchnu.fr/JunkOS/pubsub
Fetching https://git.karchnu.fr/JunkOS/ipc.cr
Fetching https://github.com/Lukc/frontd.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/RX14/multipart.cr.git
Fetching https://github.com/crystal-loot/exception_page.git
Fetching https://github.com/kemalcr/kemal-session.git
Fetching https://github.com/crystal-lang/html_builder.git
Fetching https://github.com/FartingNicoNyanCats/blogd.git
Fetching https://git.karchnu.fr/JunkOS/fs.cr
Fetching https://github.com/FartingNicoNyanCats/authd.git
Fetching https://github.com/crystal-community/jwt.git
Fetching https://github.com/stakach/openssl_ext.git
Fetching https://github.com/jeromegn/slang.git
Fetching https://github.com/faustinoaq/kemal-watcher.git
Fetching https://github.com/faustinoaq/watcher.git
Fetching https://github.com/anykeyh/clear.git
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/phoffer/inflector.cr.git
Fetching https://github.com/jwaldrip/admiral.cr.git
Fetching https://github.com/anykeyh/generate.cr.git


... and nothings more, it doesn't crash
```
something else that can help, the lib folder is not created

The output of shards update -v is attach in report.txt

[report.txt](https://github.com/crystal-lang/shards/files/3382828/report.txt)

Thanks for help
