### ISSUE TITLE
Error shard name (route) doesn't match dependency name (router)

### ISSUE THREAD

**Issue by raymanoz** [crystal-lang/shards#295]
With `Shards 0.9.0`, when I `shard install` in [our project](https://github.com/SushiChain/SushiChain), we get the message:
 > Error shard name (route) doesn't match dependency name (router)

Works with `Shards 0.8.1`

**Comment by ysbaddaden** [comment]
The `router` shard was probably renamed from `route` has some point. A reachable version has the old name in their `shard.yml`, which isn't supported (see #272). This can be fixed by specifying a minimal version, for example:

```yaml
  router:
    github: tbrand/router.cr
    version: >= 0.2.7
```
