### ISSUE TITLE
Shard infinite loop v0.9.0

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/shards#301]
```
dependencies:
  action-controller:
    github: spider-gazelle/action-controller
    version: "~> 1.8.0"
  jennifer:
    github: imdrasil/jennifer.cr
```
