### ISSUE TITLE
"shards install" halts asking for github username

### ISSUE THREAD

**Issue by InstanceOfMichael** [crystal-lang/shards#316]
```
name: kemal_app
version: 0.1.0

authors:
  - IOM <>

targets:
  kemal_app:
    main: src/app.cr

crystal: 0.32.1

license: MIT

dependencies:
  kemal:
    github: kemalcr/kemal
  spec-kemal:
    github: kemalcr/spec-kemal
    branch: master
  accord:
    github: neovintage/accord
  denetmen:
    github: izniburak/denetmen
  sentry:
    github: samueleaton/sentry
    branch: master
  kemal-session:
    github: kemalcr/kemal-session
  pg:
    github: will/crystal-pg
  kemal-pg:
    github: sdogruyol/kemal-pg
  raven:
    github: Sija/raven
```

```
$ shards install
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Fetching https://github.com/kemalcr/spec-kemal.git
Fetching https://github.com/neovintage/accord.git
Fetching https://github.com/izniburak/denetmen.git
Fetching https://github.com/samueleaton/sentry.git
Fetching https://github.com/kemalcr/kemal-session.git
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/sdogruyol/kemal-pg.git
Fetching https://github.com/ysbaddaden/pool.git
Fetching https://github.com/Sija/raven.git
Username for 'https://github.com': 
```
after adding:
```
  raven:
    github: Sija/raven
```
