### ISSUE TITLE
scripts: prebuild, etc 

### ISSUE THREAD

**Issue by kingsleyh** [crystal-lang/shards#319]
Hi,

I'd like to run a script before build occurs - so what do you think about an extra hook:

```yml
scripts:
  postinstall: make 
  prebuild: touch foo.txt
```

Other helpful hooks could be:
* preinstall
* postbuild
