### ISSUE TITLE
install runs out of memory in 0.9

### ISSUE THREAD

**Issue by c-cesar** [crystal-lang/shards#338]
To install a basic setup of Kemal with Crceto I had to downgrade shards to 0.8.1, because 0.9.0 runs out of memory on a system with 8 GB if RAM.
Using Arch Linux default packages.

shards.yml working on shards 0.8.1
```
dependencies:
  kemal:
    github: kemalcr/kemal
  kilt:
    github: jeromegn/kilt
  slang:
    github: jeromegn/slang
  sqlite3:
    github: crystal-lang/crystal-sqlite3
    version: ~> 0.14.0
  crecto:
    github: Crecto/crecto
```

Downstream report: https://github.com/amberframework/micrate/issues/46
