### ISSUE TITLE
Error when version conflict should say what shards need the conflicting version

### ISSUE THREAD

**Issue by c-cesar** [crystal-lang/shards#339]
When installing shards that need conflicting versions I get:
`Error resolving db (~> 0.8.0, *, ~> 0.7.0)`
Ideally, this should give me the name of the shards requesting each version, as:
`Error resolving db (sqlite3: ~> 0.8.0, *, crecto: ~> 0.7.0)`

OBS:
Reporting against 0.8.1. Not tested on shards 0.9 because of #338

**Comment by waj** [comment]
@c-cesar the solver algorithm has changed for the (not yet released) version 0.10: https://github.com/crystal-lang/shards/pull/322

That means the error messages have changed (hopefully improved). Do you want to try again with the version at master branch? Or share your `shard.yml` (and `shard.lock`) if possible so I can use it as a test case.

**Comment by c-cesar** [comment]
The shards.yml that shows the conflict is on #338. To resolve, the conflict I specified a previous sqlite version, so this would give the message. 
```
dependencies:
  kemal:
    github: kemalcr/kemal
  kilt:
    github: jeromegn/kilt
  slang:
    github: jeromegn/slang
  sqlite3:
    github: crystal-lang/crystal-sqlite3
  crecto:
    github: Crecto/crecto
```
