### ISSUE TITLE
Missing "v1.0.0:shard.yml"

### ISSUE THREAD

**Issue by mamantoha** [crystal-lang/shards#346]
Hi there.

There is an issue with installing some shards after updating to Crystal 0.34.0.

Steps to reproduce:

* Create new lib (e.g. `crystal init lib test_redis`)
* Add dependency to `shard.yml`
  ```yml
  dependencies:
    redis:
      github: stefanwille/crystal-redis
  ```
* Run `shards`

Output:

```
Missing "v1.0.0:shard.yml" for "redis"
```

Previously it took the latest version from the master branch.

```
shards --version
Shards 0.10.0 [4091ac5] (2020-04-06)
```

```
crystal --version
Crystal 0.34.0 [4401e90f0] (2020-04-06)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by straight-shoota** [comment]
I noticed this error, too.

The reason is that `redis@1.0.0` doesn't provide a `shard.yml` but `shards` tries to read all older releases to figure out which dependencies match. A version that doesn't provide a `shard.yml` should just be ignored instead of failing. I think that's how this worked before 0.10.0.

A quick fix is to pin the shard to a specific version. For example
```yaml
dependencies:
  redis:
    github: stefanwille/crystal-redis
    version: 2.5.3
```
This avoids shards trying to read `shard.yml` of oder releases.
