### ISSUE TITLE
Issue with clearing cache

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/shards#398]
I have a private shard that my app uses. Right now I just point it to master branch. 
When I do these steps, I seem to run in to a cache issue.
* Make update to shard
* Push master to github
* run `shards update` from project
* boot project and get error because it never actually updated the shard
* `rm -rf lib/my_shard`
* `shards install`
* boot project and now it's all good.

```
$ shards --version
Shards 0.10.0 (2020-04-06)
$ crystal -v
Crystal 0.34.0 (2020-04-07)

LLVM: 10.0.0
Default target: x86_64-apple-macosx
```

This is how I have my shard defined.

```
dependencies:
  my_shard:
    git: https://jwoertink:abc@github.com/group/my_shard.cr
    branch: master
```
