### ISSUE TITLE
Adding the requirer to shard.lock

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/shards#433]
I thought this issue existed already, but I didn't see it. It would be nice if we looked in the shard.lock file to see which shard required the shards. I'm mainly talking about the sub dependencies.

If I have this shard.yml

```
dependencies:
  teeplate:
    github: luckyframework/teeplate
    version: ~> 0.8.2

development_dependencies:
  ameba:
    github: crystal-ameba/ameba
    version: ~> 0.13
```

And my shard.lock looks like

```
shards:
  ameba:
    git: https://github.com/crystal-ameba/ameba.git
    version: 0.13.2

  future:
    git: https://github.com/crystal-community/future.cr.git
    version: 0.1.0

  teeplate:
    git: https://github.com/luckyframework/teeplate.git
    version: 0.8.2
```

I never required `future`, so which shard did? Now, I know that it could either be teeplate, or ameba, but it could also be both. So maybe it looks like:

```
shards:
  ameba:
    git: https://github.com/crystal-ameba/ameba.git
    version: 0.13.2

  future:
    git: https://github.com/crystal-community/future.cr.git
    version: 0.1.0
    dependency_of:
      - ameba
      - teeplate

  teeplate:
    git: https://github.com/luckyframework/teeplate.git
    version: 0.8.2
```

In my case, I have a specific shard that is having some issues in Lucky stopping it from running a `shards install`, but I don't know where it's coming from without going through each of the dependencies to see what's requiring it.
