### ISSUE TITLE
Shards override pulling release instead of branch

### ISSUE THREAD

**Issue by Xosmond** [crystal-lang/shards#440]
I'm getting one problem. Looks like when using override, it ignores `branch` and it pull the latest release instead of the branch.

shard.override.yml

```yml
dependencies:
  avram:
    github: xosmond/avram
    branch: master
```

PD: Tried with commit, and it works fine.

```yml
dependencies:
  avram:
    github: xosmond/avram
    commit: b1c1371df3485a0fcb0b78f24be018f20f4e2356
```
