### ISSUE TITLE
`shards outdated` lists `branch: master` as outdated

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/shards#446]
`shards outdated` seems to treat branch-based dependencies always as outdated, even if they really aren't.

```yaml
name: outdated
version: 0.1.0

dependencies:
  crinja:
    github: straight-shoota/crinja
    branch: master
```

```console
$ shards outdated
Resolving dependencies
Fetching https://github.com/straight-shoota/crinja.git
Outdated dependencies:
  * crinja (installed: 0.6.1 at e1fa175)
```

`e1fa175` is the latest commit on master.
