### ISSUE TITLE
github ambiguous sources

### ISSUE THREAD

**Issue by stakach** [crystal-lang/shards#470]
I'm getting some ambiguous sources errors when updating shards.
I have solved the problem temporarily by using shard.override however I think there is a better way, at least for github

The issue is that two separate shards are depending on `retriable`

```yaml
dependencies:
  retriable:
    github: Sija/retriable.cr
```

and

```yaml
dependencies:
  retriable:
    github: sija/retriable.cr
```

note the difference in case on `sija`

However github is case insensitive when if comes to URLs so I propose that for github dependencies the URLs are downcased to avoid errors like this:

```
Error shard name (retriable) has ambiguous sources: 'git: https://github.com/Sija/retriable.cr.git' and 'git: https://github.com/sija/retriable.cr.git'.
```

which would greatly improve the experience of using shards
