### ISSUE TITLE
Not getting latest version of dependency

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/shards#472]
I may be missing something as it's late, but I noticed when doing a shards install/update, it's not installing the latest version of that shard's dependencies.

With a `shard.yml` like:

```yaml
dependencies:
  athena:
    github: athena-framework/athena
```

Running `shards install` produces the following lock file:

```yaml
version: 2.0
shards:
  amber_router:
    git: https://github.com/amberframework/amber-router.git
    version: 0.4.4

  athena:
    git: https://github.com/athena-framework/athena.git
    version: 0.12.0

  athena-config:
    git: https://github.com/athena-framework/config.git
    version: 0.1.3

  athena-dependency_injection:
    git: https://github.com/athena-framework/dependency-injection.git
    version: 0.2.3

  athena-event_dispatcher:
    git: https://github.com/athena-framework/event-dispatcher.git
    version: 0.1.2

  athena-serializer:
    git: https://github.com/athena-framework/serializer.git
    version: 0.2.3

  athena-validator:
    git: https://github.com/athena-framework/validator.git
    version: 0.1.3
```

I would have expected the serializer and dependency injection shards to be updated to `0.2.4` as I recently released those versions, and they are defined as `version: ~> 0.2.2` in Athena's `shard.yml`.  If installing either the dependency injection shard or the serializer on their own, the correct version of `0.2.4` is used within the lock file.

EDIT:  Tested with both `0.12.0` and `0.13.0`.
