### ISSUE TITLE
Wrong shard version in "shards outdated"

### ISSUE THREAD

**Issue by petr-fischer** [crystal-lang/shards#486]
I have this in my `shard.yml`:

```
...
dependencies:
  neo4j:
    github: jgaskins/neo4j.cr
  amqp-client:
    github: cloudamqp/amqp-client.cr
  raven:
    github: Sija/raven.cr
```

My `shard.lock`:

```
...
neo4j:
    git: https://github.com/jgaskins/neo4j.cr.git
    version: 0.6.0
...
```

`shards list` output:

```
...
  * neo4j (0.6.0)
  * amqp-client (0.6.6)
  * amq-protocol (0.3.24)
  * raven (1.9.1)
...
```

**But** when I run `shards outdated`, this is the output:

```
Unable to satisfy the following requirements:
...
- `crystal (~> 0.27, >= 0.27.0)` required by `neo4j 0.5.5`
Failed to resolve dependencies, try updating incompatible shards or use --ignore-crystal-version as a workaround if no update is available.
```

Why there is version neo4j 0.5.5 in the output? If I check `lib/neo4j/shard.yml` file, there is correct `0.6.0` version. I'm confused.

I deleted `~/.cache/crystal` and `~/.cache/shards`, but still the same output.

```
Ubuntu 20.10

➤  crystal --version
Crystal 1.0.0 [dd40a2442] (2021-03-22)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu

➤  shards --version
Shards 0.14.1 [addc26a] (2021-03-10)
```
