### ISSUE TITLE
Failed to clone on Arch lInux

### ISSUE THREAD

**Issue by kostya** [crystal-lang/shards#497]
```
Crystal 1.0.0 [dd40a2442] (2021-03-22)
Shards 0.14.1 [addc26a] (2021-03-10)
Arch Linux
```

```
dependencies:
  clear:
    github: anykeyh/clear
    branch: master
```

`shards update`
```
shards update
Resolving dependencies
Fetching https://github.com/anykeyh/clear.git
Fetching https://github.com/jwaldrip/admiral.cr.git
Fetching https://github.com/anykeyh/generate.cr.git
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/anykeyh/inflector.cr.git
Failed to clone https://github.com/anykeyh/inflector.cr.git
```

but `git clone https://github.com/anykeyh/inflector.cr.git` locally work.
