### ISSUE TITLE
`postinstall` flexibility

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/shards#507]
Gitter discussion provided to save time and not misquote @oprypin .

@oprypin 
> i see. well, maybe my main dissatisfaction comes from how rigid postinstall is. any tiniest problem and everything just bails out
and you're basically taking on a task of maintaining a fully universal build of a lib.

@didactic-drunk
> Yes. If only postinstall allowed

```
postinstall:
  linux-musl: ./build/linux-musl.sh # needs variant for some reason
  linux: ./build/linux.sh
  windows-msvc: ./build/windows-msvc.cmd
  windows-mingw: ./build/windows-mingw.cmd
  posix-default: cd build/posix && make
  windows-default: cd build/windows && make
  default: make
```

> And tried keys in order of most specific to less specific arch trying posix-default or windows-default 2nd to last before default.

@oprypin
> @didactic-drunk: well it looks like you're already miles ahead of the rest in terms of thinking this through. I'd support this

### Why my build scripts are so complicated

Attempting to improve UX (developer experience DX, is that thing?). There are 3 unix use cases. 1) Building a rpm/deb package (or personal executable) that relies on the distribution packaged libraries. 2) Building a run on any distro binary that can't rely on a system installed libsodium. 3) Same as 1 but the system libsodium is ancient and can't be used (This is very common). The build scripts check the system version (but allow overrides) and uses them by default if new enough otherwise download and build the version tested with sodium.cr. None of this is a concern for windows which never has a packaged libsodium

`shards install` takes care of everything unless you want to override a value provides the best DX even if the build script is more complex. I doubt I'd have half as many users if it required: manually check your distro version. If it's >= x install else download and build it yourself.

Assume you make a program using compression and encryption (not too uncommon).  I'll use `zstd.cr` and `sodium.cr` for this example.  More than half the time `zstd` **and** `libsodium` are too old and need to download a newer version.  For windows it always requires downloading a prebuilt package.  If I ask users to do this manually the friction in either building for their own use or forking to make a small improvement is too large.

Not just building.  Do I ask them to check `sha256` and `minisign`?  

Can't I just let the user handle it?  On windows.  Click download.  Find the download.  Move it to the build directory.  Unzip it.  Rename from libsodium-1.0.18 to libsodium or have a complicated build script that attempts to use the latest version in the specified directory.  If I go with a build script finding the version I may as well just download and unzip it for them and I'm back where I started.
