### ISSUE TITLE
Issue specifying version 

### ISSUE THREAD

**Issue by stakach** [crystal-lang/shards#544]
When specifying dependencies with `>=` I'm getting this error.
Works fine when specifying crystal versions and the readme seems to indicate that this should work for dependencies

```yaml
dependencies:
  placeos-driver:
    github: placeos/driver
    version: ">= 5.0.0"
```

![image](https://user-images.githubusercontent.com/368013/153965003-848f8d37-ba47-4be5-979e-85428d973476.png)

Simple enough to work around however thought it worth creating an issue

**Comment by Blacksmoke16** [comment]
What version of shards are you using? I'm unable to reprodce this by just creating a `shard.yml` with:

```yaml
dependencies:
  placeos-driver:
    github: placeos/driver
    version: ">= 5.0.0"
```
and running `shards install`.
