### ISSUE TITLE
Installed version in `lib` does not match version in `shard.lock`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/shards#581]
_Originally posted by @jwoertink in https://github.com/crystal-lang/shards/issues/572#issuecomment-1468568825_

I [@jwoertink] did a soft release of Lucky and Avram 1.0.0 over the weekend, and now my apps won't pull 1.0.0-rc1 anymore. 

My shard.yml file has this:

```yml
dependencies:
  lucky:
    github: luckyframework/lucky
    version: 1.0.0-rc1
  avram:
    github: luckyframework/avram
    version: 1.0.0-rc1
```

I run `rm -rf lib/ shard.lock ~/.cache/` then `shards install`. When it's installing, I see this:

![image](https://user-images.githubusercontent.com/2391/225094111-77767b67-0ab9-4219-872b-6167407ddc46.png)

My shard.lock file has the correct version:

```
❯ cat shard.lock 
version: 2.0
shards:
  CrystalEmail:
    git: https://github.com/jwoertink/crystalemail.git
    version: 0.2.6+git.commit.960e1b9ad02288ae56110d39fe9d7ca3bbcdcd1e

  ameba:
    git: https://github.com/crystal-ameba/ameba.git
    version: 1.3.1

  authentic:
    git: https://github.com/luckyframework/authentic.git
    version: 0.9.0

  authly:
    git: https://github.com/azutoolkit/authly.git
    version: 1.2

  avram:
    git: https://github.com/luckyframework/avram.git
    version: 1.0.0-rc1
...
  lucky:
    git: https://github.com/luckyframework/lucky.git
    version: 1.0.0-rc1
```

Running `shards list --tree` shows the correct list

```
❯ shards list --tree
Shards installed:
  * lucky (1.0.0-rc1)
    * lucky_task (0.1.1)
    * habitat (0.4.7)
    * wordsmith (0.4.0)
    * lucky_router (0.5.1)
    * shell-table (0.9.3)
    * cry (0.4.3)
    * exception_page (0.3.0)
      * backtracer (1.2.2)
    * dexter (0.3.4)
    * pulsar (0.2.3)
    * teeplate (0.8.5)
  * avram (1.0.0-rc1)
    * lucky_task (0.1.1)
    * pg (0.26.0)
      * db (0.11.0)
    * habitat (0.4.7)
```

but the actual versions that show up in `lib` are wrong...

```
❯ cat lib/lucky/shard.yml 
name: lucky
version: 1.0.0

crystal: ">=1.6.0"

❯ cat lib/avram/shard.yml 
name: avram
version: 1.0.0

crystal: ">= 1.6.0"
```

These are installing `1.0.0` and not `1.0.0-rc1` even though it's saying that it is.

Now one very strange thing is, after I run `shards install`, if I `rm -rf lib/lucky/` then `shards update lucky` that will install the rc1 version. It only installs the wrong version on `shards install` and `shards update`. 

Edit: using shards `0.17.2`
