### ISSUE TITLE
Too strict ambiguous source checker

### ISSUE THREAD

**Issue by rmarronnier** [crystal-lang/shards#590]
A `shards install` using

```yaml
dependencies:
  redis:
    github: jgaskins/redis
```
results in :

```bash
Error shard name (redis) has ambiguous sources: 'git: https://github.com/jgaskins/redis.git' and 'git: https://github.com/stefanwille/crystal-redis.git'.
```

Is this intended behaviour ?
