### ISSUE TITLE
"Error creating symlink" as a result of dependency project that has lib folder

### ISSUE THREAD

**Issue by ExpliuM** [crystal-lang/shards#598]
Terminal output
```bash
Resolving dependencies
Fetching https://github.com/project-osrm/osrm-backend.git
Shard "osrm-backend" version (5.24.0) doesn't have a shard.yml file
Installing osrm-backend (5.24.0)
Unhandled exception: Error creating symlink: '..' -> '/home/V09118B/projects/osrm_backend/lib/osrm-backend/lib': File exists (File::AlreadyExistsError)
  from /crystal/src/crystal/system/unix/file.cr:109:11 in 'install'
  from /shards/src/commands/install.cr:72:11 in 'run'
  from /shards/src/cli.cr:100:9 in '->'
  from /crystal/src/primitives.cr:266:3 in 'parse'
  from /shards/src/cli.cr:145:3 in '__crystal_main'
  from /crystal/src/crystal/main.cr:110:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

shard.yml:
```yml
name: osrm-backend
version: 0.1.0
crystal: 1.0.0

repository: https://github.com/Project-OSRM/osrm-backend

dependencies:
  osrm-backend:
    github: Project-OSRM/osrm-backend
    version: ~> 5.24.0
```
