### ISSUE TITLE
Shards override development_dependencies doesn't work on Windows

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/shards#655]
I'm trying to test an update locally on Windows, and I'm not able to use the shard override for `development_dependencies`.

```yml
# shard.yml
name: test
version: 0.1.0
crystal: '>= 1.14.0'
license: MIT
development_dependencies:
  db:
    github: crystal-lang/crystal-db
    version: 0.13.1
```

```yml
# shard.override.yml
development_dependencies:
  db:
    github: crystal-lang/crystal-db
    branch: master
```

```powershell
> $env:SHARDS_OVERRIDE = 'shard.override.yml'
> shards install
```

However, I do see that overrides from `dependencies` make it over. It seems to be just the `development_dependencies` that are ignored.

### Expected Output

The install output should say "Installing db (0.13.1 at 892c256)"
Checking inside of the `lib\db\src` I expected to see changes made since the 0.13.1 release.

### Actual Output

The install output says "Installing db (0.13.1)" and the lib dir shows code from `3eaac85`

**Comment by straight-shoota** [comment]
This is not specific to Windows. The same thing happens on Linux.

It looks like overrides only apply to `dependencies`, not to `development_dependencies`:

https://github.com/crystal-lang/shards/blob/9a5e5b627410573b759bd92871e6850bcb7bd54a/src/molinillo_solver.cr#L46

I'm not sure if this is completely intentional or just an omission.
The documentation only mentions that the override file provides overrides for `dependencies` (https://github.com/crystal-lang/shards/blob/master/docs/shards.adoc#files), although the language is a bit fuzzy because both `dependencies` and `development_dependencies` are categories of dependencies.

**Comment by straight-shoota** [comment]
I suppose a possible explanation is that shards does not install nested `development_dependencies`, only those defined in the top `shard.yml`. So it's considerably more straightforward to override them there directly, compared to overriding nested dependencies' `shard.yml`.

Having to edit `shard.yml` directly is still not convenient for keeping a local override outside of `git` and consistent across branches etc. So I guess it makes sense to add overrides for `development_dependencies` as well.

**Comment by miry** [comment]
I believe I’m experiencing a related issue.

My project’s shard.yml includes:

```yaml
dependencies:
  marten:
    github: miry/marten
    branch: master

  pg:
    github: will/crystal-pg
    branch: master
    commit: cafe112f2847f366262460ee999e74f9c7e8b31c
```

Meanwhile, the `marten` project declares `pg` as a development dependency:

```yaml
development_dependencies:
  pg:
    github: will/crystal-pg
```

NOTE: There’s a difference in the `commit` — my project pins `pg` to a specific commit, while `marten` does not.
When I run:

```shell
$ shard update marten
...
Using pg (0.29.0 at cafe112)
```

It seems like `lib/pg` is replaced with the released version from GitHub (0.29.0), 
but the `shard.lock` file still references the specific commit (`cafe112...`).
Additionally, `.shards.info` shows a mismatch — it points to the latest release commit instead of the frozen one.

Here’s the diff:

```diff
   pg:
     git: https://github.com/will/crystal-pg.git
-    version: 0.29.0+git.commit.cafe112f2847f366262460ee999e74f9c7e8b31c
+    version: 0.29.0
```


PS: To help debug this, I started adding more context to log messages: https://github.com/crystal-lang/shards/pull/674/files
