### ISSUE TITLE
Include compiler options in shard.yml

### ISSUE THREAD

**Issue by plambert** [crystal-lang/shards#671]
It would be nice, when writing something that needs `-Dpreview_mt`, to not have to remember to include it in the shards build.  Especially if there are several targets and they require different compiler arguments.

For example…

```YAML
name: my_project
version: 0.10.0

authors:
  - Someone Interesting <someone@interesting>

compiler: 
  args: --error-trace --release  --progress --verbose

targets:
  foo-server:
    main: src/server.cr
    compiler: -Dpreview_mt -Dexecution_context
  foo-cli:
    main: src/cli.cr
  foo-util:
    main: src/util.cr
```

This would build every target with the `--error-trace` and `--release` and other arguments given at the top level, and add `-Dpreview_mt -Dexecution_context` for just the `foo-server` target.

Does this seem reasonable?  Laziness isn't always a bad thing, and it'd reduce mistakes—at least for me.
