### ISSUE TITLE
Race Condition Between Dependencies and Their Subdependencies on Update

### ISSUE THREAD

**Issue by miry** [crystal-lang/shards#675]
I believe I’m experiencing a related issue.

My project’s shard.yml includes:

```yaml
dependencies:
  marten:
    github: miry/marten
    branch: master

  pg:
    github: will/crystal-pg
    # branch: master
    commit: cafe112f2847f366262460ee999e74f9c7e8b31c   # unreleased 0.29.0
```

Meanwhile, the `marten` project declares `pg` as a development dependency:

```yaml
development_dependencies:
  pg:
    github: will/crystal-pg
```

NOTE: There’s a difference in the `commit` — my project pins `pg` to a specific commit, while `marten` does not.
When I run:

```shell
$ shard update marten
...
Using pg (0.29.0 at cafe112)
```

It seems like `lib/pg` is replaced with the released version from GitHub (0.29.0), 
but the `shard.lock` file still references the specific commit (`cafe112...`).
Additionally, `.shards.info` shows a mismatch — it points to the latest release commit instead of the frozen one.

Here’s the diff:

```diff
   pg:
     git: https://github.com/will/crystal-pg.git
-    version: 0.29.0+git.commit.cafe112f2847f366262460ee999e74f9c7e8b31c
+    version: 0.29.0
```

## Workaround

In case someone else runs into the same issue — the fix for lib/pg is simply to run:

```shell
$ shards update pg
```

PS: To help debug this, I started adding more context to log messages: https://github.com/crystal-lang/shards/pull/674/files

**Comment by ysbaddaden** [comment]
I think having both `branch` _and_ `commit` is the issue. On update the resolver might only consider the branch ref, and overlook the commit ref.

**Comment by miry** [comment]
> I think having both branch and commit is the issue. On update the resolver might only consider the branch ref, and overlook the commit ref.

I have tested with only commit or branch.

**Comment by miry** [comment]
Here are my small observations around the `branch` vs. `commit` directive usage:

`shards.lock` looks like:

```yaml
  pg:
    git: https://github.com/will/crystal-pg.git
    version: 0.29.0+git.commit.cafe112f2847f366262460ee999e74f9c7e8b31c
```

1. Using both `branch` and `commit` at the same time or only single `branch: master`

```yaml
dependencies:
  marten:
    github: miry/marten
    branch: master

  pg:
    github: will/crystal-pg
    branch: master
    commit: cafe112f2847f366262460ee999e74f9c7e8b31c   # unreleased 0.29.0
```

```shell
$ ~/src/crystal/shards/shard update marten | grep pg
D: [pg] git ls-remote --get-url origin
I: Fetching https://github.com/will/crystal-pg.git
D: [pg] git config --get remote.origin.mirror
D: [pg] git fetch --all --quiet
D: [pg] git ls-tree -r --full-tree --name-only cafe112f2847f366262460ee999e74f9c7e8b31c -- shard.yml
D: [pg] git show cafe112f2847f366262460ee999e74f9c7e8b31c:shard.yml
D: [pg] git log -n 1 --pretty=%H refs/heads/master
D: [pg] git ls-tree -r --full-tree --name-only refs/heads/master -- shard.yml
D: [pg] git show refs/heads/master:shard.yml
D: [pg] git ls-tree -r --full-tree --name-only cafe112f2847f366262460ee999e74f9c7e8b31c -- shard.yml
D: [pg] git show cafe112f2847f366262460ee999e74f9c7e8b31c:shard.yml
I: Using pg (0.29.0 at cafe112)
```

I see that during the upgrade it fetches 3 times pg. 2 of them are correct versions `cafe112f2847f366262460ee999e74f9c7e8b31c` and only second time it uses: `refs/heads/master`.

I see that during the upgrade, pg is fetched three times. Two of them are for the correct version `cafe112f2847f366262460ee999e74f9c7e8b31c`, and only the second time it uses `refs/heads/master`.

2. Using only the `commit` directive:

```yaml
dependencies:
  marten:
    github: miry/marten
    branch: master

  pg:
    github: will/crystal-pg
    commit: cafe112f2847f366262460ee999e74f9c7e8b31c   # unreleased 0.29.0
```

```shell
$ ~/src/crystal/shards/shard update marten | grep pg
D: [pg] git ls-remote --get-url origin
I: Fetching https://github.com/will/crystal-pg.git
D: [pg] git config --get remote.origin.mirror
D: [pg] git fetch --all --quiet
D: [pg] git ls-tree -r --full-tree --name-only cafe112f2847f366262460ee999e74f9c7e8b31c -- shard.yml
D: [pg] git show cafe112f2847f366262460ee999e74f9c7e8b31c:shard.yml
D: [pg] git log -n 1 --pretty=%H cafe112f2847f366262460ee999e74f9c7e8b31c
D: [pg] git ls-tree -r --full-tree --name-only cafe112f2847f366262460ee999e74f9c7e8b31c -- shard.yml
D: [pg] git show cafe112f2847f366262460ee999e74f9c7e8b31c:shard.yml
D: [pg] git ls-tree -r --full-tree --name-only cafe112f2847f366262460ee999e74f9c7e8b31c -- shard.yml
D: [pg] git show cafe112f2847f366262460ee999e74f9c7e8b31c:shard.yml
I: Using pg (0.29.0 at cafe112)
```

I see that during the upgrade, pg is fetched three times — all referencing the correct commit `cafe112f2847f366262460ee999e74f9c7e8b31c`.
However, the contents of `lib/pg` are from the `0.29.0` version, not the commit.

```diff
diff --git a/lib/.shards.info b/lib/.shards.info
index 9d0bee9..49641e4 100644
--- a/lib/.shards.info
+++ b/lib/.shards.info
@@ -18,10 +18,10 @@ shards:
     version: 1.3.4
   marten:
     git: https://github.com/miry/marten.git
-    version: 0.5.6+git.commit.a5aa7b3c27756d78ad87e5d908935aed9992cec9
+    version: 0.5.6+git.commit.469058f5e5e158fc367de3b2b9439478ef408776
   pg:
     git: https://github.com/will/crystal-pg.git
-    version: 0.29.0+git.commit.cafe112f2847f366262460ee999e74f9c7e8b31c
+    version: 0.29.0
   openssl_ext:
     git: https://github.com/spider-gazelle/openssl_ext.git
     version: 2.4.4
```
