### ISSUE TITLE
Shards installing a different version of a shard than what's shown in output

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/shards#680]
I ran in to this issue where my app has

```yaml
dependencies:
  avram:
    github: luckyframework/avram
    version: ~> 1.3.0
development_dependencies:
  breeze:
    github: luckyframework/breeze
    branch: main
```

Then Breeze also has Avram set as a dependency

```yaml
dependencies:
  avram:
    github: luckyframework/avram
    version: ~> 1.0
```

When I pushed this up to my CI, I have a step that runs `shards install`, and in this step, the output clearly says Installing Avram 1.3.0

![Image](https://github.com/user-attachments/assets/125a83db-114c-4cf9-99ff-4b15aedd974f)

However, it's actually installing Avram 1.4.0. I'm able to verify this because Avram 1.4.0 introduced some deprecation warnings, and new features that are causing the CI to fail.

![Image](https://github.com/user-attachments/assets/d372e439-884a-437f-b9ea-3dc69202729a)

Using shards v0.18.0

Maybe related? https://github.com/crystal-lang/shards/issues/675
