### ISSUE TITLE
Error shard name doesn't match dependency name

### ISSUE THREAD

**Issue by Fahrradflucht** [crystal-lang/shards#97]
I don't fully get what change https://github.com/crystal-lang/shards/commit/f2e4c72efb03a10d402394a531fdc92e93159033 introduced.

My problem is that I get  `Error shard name (pg) doesn't match dependency name (crystal-pg)` with a shard.yml file like this:

```
name: crystal_api_sample
version: 0.1.0

authors:
  - Fahrradflucht <mail@mathiswiehl.de>

dependencies:
  crystal_api:
    github: akwiatkowski/crystal_api
    
license: MIT
```

but if I run `shard update` in [crystal_api](https://github.com/akwiatkowski/crystal_api) itself I don't get the error and everything works just fine...

Isn't that super absurd? I mean I'm pulling the same dependencies through the same shard.yml file.

**Comment by ysbaddaden** [comment]
I'll have a look, that should indeed not happen.

**Comment by ysbaddaden** [comment]
The problem is that `shard.yml` for crystal_api v0.3.2 has `crystal-pg` as a dependency when it should be `pg`. The problem is fixed in master, so you must tell Shards to use this refs, and not the latest release (which is the default):

```yml
dependencies:
  crystal_api:
    github: akwiatkowski/crystal_api
    branch: master
```

Alternatively you may ask @akwiatkowski to make a new release of crystal_api :)

The error message could be improved. Maybe when resolving dependencies of a dependency, it could tell what dependency+version is causing the problem, so it's more obvious.
